/**
 * GENERATED by a rig that has since been deleted (see AGENTS.md). These are art
 * now, not build output: they cannot be regenerated and the game still loads
 * them for Akira, Takeshi and the `lord` class. Do not delete.
 *
 * These three sheets are drawn by posing a rig rather than by hand, so the
 * frame numbers, sheet size and anchor below are measured at build time and can
 * never drift from the PNG the way hand-written values did.
 */
import shigeruSheet from '../../assets/sprites/shigeru-battle.png';
import akiraSheet from '../../assets/sprites/akira-battle.png';
import takeshiSheet from '../../assets/sprites/takeshi-battle.png';
import type { SpriteSheet } from './spriteSheetConfig';

export const GENERATED_SHEETS: Record<string, SpriteSheet> = {
  shigeru: {
    url: shigeruSheet,
    cols: 8,
    rows: 6,
    sheetW: 1664,
    sheetH: 1152,
    pixelArt: false,
    content: {
      cx: 0.5,
      bottom: 0.8229,
      height: 0.625,
    },
    clips: {
      idle: { frames: [0, 1, 2, 3, 4, 5], fps: 6, loop: true },
      walk: { frames: [8, 9, 10, 11, 12, 13], fps: 10, loop: true },
      attack: { frames: [16, 17, 18, 19, 20, 21], fps: 14, loop: false },
      crit: { frames: [24, 25, 26, 27, 28, 29, 30, 31], fps: 14, loop: false },
      dodge: { frames: [32, 33, 34, 35], fps: 14, loop: false },
      hit: { frames: [36, 37, 38], fps: 12, loop: false },
      die: { frames: [40, 41, 42, 43, 44], fps: 9, loop: false },
    },
  },
  akira: {
    url: akiraSheet,
    cols: 8,
    rows: 6,
    sheetW: 1920,
    sheetH: 1152,
    pixelArt: false,
    content: {
      cx: 0.4833,
      bottom: 0.8958,
      height: 0.6458,
    },
    clips: {
      idle: { frames: [0, 1, 2, 3, 4, 5], fps: 6, loop: true },
      walk: { frames: [8, 9, 10, 11, 12, 13], fps: 10, loop: true },
      attack: { frames: [16, 17, 18, 19, 20, 21], fps: 14, loop: false },
      crit: { frames: [24, 25, 26, 27, 28, 29, 30, 31], fps: 14, loop: false },
      dodge: { frames: [32, 33, 34, 35], fps: 14, loop: false },
      hit: { frames: [36, 37, 38], fps: 12, loop: false },
      die: { frames: [40, 41, 42, 43, 44], fps: 9, loop: false },
    },
  },
  takeshi: {
    url: takeshiSheet,
    cols: 8,
    rows: 6,
    sheetW: 1792,
    sheetH: 1248,
    pixelArt: false,
    content: {
      cx: 0.4821,
      bottom: 0.8942,
      height: 0.5481,
    },
    clips: {
      idle: { frames: [0, 1, 2, 3, 4, 5], fps: 6, loop: true },
      walk: { frames: [8, 9, 10, 11, 12, 13], fps: 10, loop: true },
      attack: { frames: [16, 17, 18, 19, 20, 21], fps: 13, loop: false },
      crit: { frames: [24, 25, 26, 27, 28, 29, 30, 31], fps: 13, loop: false },
      dodge: { frames: [32, 33, 34, 35], fps: 13, loop: false },
      hit: { frames: [36, 37, 38], fps: 12, loop: false },
      die: { frames: [40, 41, 42, 43, 44], fps: 8, loop: false },
    },
  },
};
