// A side-view humanoid (and horse) drawn from joint angles.
//
// Frames are generated by posing this rig, not by hand-placing pixels, which is
// what makes seven animation clips per character affordable. Everything is in
// final frame pixels with the origin at the character's feet, +x facing right —
// the direction the art must face, because the game mirrors with scaleX(-1).

import { capsule, ellipse, tone, lerp2 } from './raster.mjs';

/** Build a three-tone material from one base colour. */
export function mat(base, line = '#161020', lightT = 0.3, shadeT = -0.32) {
  return { line, base, light: tone(base, lightT), shade: tone(base, shadeT) };
}

/** Direction of a limb at `deg`, where 0 hangs straight down. */
function dir(deg) {
  const r = (deg * Math.PI) / 180;
  return [Math.sin(r), Math.cos(r)];
}

function along(from, deg, len) {
  const d = dir(deg);
  return [from[0] + d[0] * len, from[1] + d[1] * len];
}

/** Default proportions, in px, for a ~117px-tall figure. */
export const PROPORTIONS = {
  ankle: -7,
  knee: -33,
  hip: -58,
  waist: -66,
  chest: -84,
  shoulder: -92,
  neck: -96,
  headY: -107,
  headRX: 10,
  headRY: 11.5,
  shoulderW: 13.5,
  hipW: 9,
  upperArm: 21,
  foreArm: 21,
  thigh: 26,
  shin: 26,
  armR: 4.6,
  legR: 5.4,
};

export const REST_POSE = {
  bob: 0,
  lean: 0,
  headTilt: 0,
  turn: 0,
  armFar: { sh: 8, el: 18 },
  armNear: { sh: -6, el: 22 },
  legFar: { hip: 6, knee: -6 },
  legNear: { hip: -6, knee: 6 },
  weaponRot: 0,
  weaponSlide: 0,
};

export function pose(overrides = {}) {
  return {
    ...REST_POSE,
    ...overrides,
    armFar: { ...REST_POSE.armFar, ...overrides.armFar },
    armNear: { ...REST_POSE.armNear, ...overrides.armNear },
    legFar: { ...REST_POSE.legFar, ...overrides.legFar },
    legNear: { ...REST_POSE.legNear, ...overrides.legNear },
  };
}

/**
 * Where every joint ends up for a pose. Callers need this to hang a weapon off
 * the near hand or a cape off the shoulders without duplicating the maths.
 */
export function solve(p, P = PROPORTIONS) {
  const lean = p.lean;
  const hipY = P.hip + p.bob;

  // Torso rotates about the hip, so leaning does not lift the feet.
  const rot = (pt) => {
    const r = (lean * Math.PI) / 180;
    const dx = pt[0];
    const dy = pt[1] - hipY;
    return [dx * Math.cos(r) - dy * Math.sin(r), hipY + dx * Math.sin(r) + dy * Math.cos(r)];
  };

  const shoulderC = rot([0, P.shoulder + p.bob]);
  const neck = rot([0, P.neck + p.bob]);
  const head = rot([0, P.headY + p.bob]);
  const chest = rot([0, P.chest + p.bob]);
  const waist = rot([0, P.waist + p.bob]);

  // The far shoulder sits well back of the near one so a sliver of the far arm
  // always clears the torso — otherwise the figure reads as one-armed.
  const shFar = [shoulderC[0] - P.shoulderW * 0.62, shoulderC[1] + 1];
  const shNear = [shoulderC[0] + P.shoulderW * 0.24, shoulderC[1] + 2];

  const arm = (sh, a) => {
    const elbow = along(sh, a.sh + lean, P.upperArm);
    const hand = along(elbow, a.sh + a.el + lean, P.foreArm);
    return { shoulder: sh, elbow, hand };
  };

  const hipFar = [-P.hipW * 0.45, hipY];
  const hipNear = [P.hipW * 0.45, hipY];
  const leg = (h, a) => {
    const knee = along(h, a.hip, P.thigh);
    const foot = along(knee, a.hip + a.knee, P.shin);
    return { hip: h, knee, foot };
  };

  return {
    hipY,
    lean,
    shoulderC,
    neck,
    head,
    chest,
    waist,
    armFar: arm(shFar, p.armFar),
    armNear: arm(shNear, p.armNear),
    legFar: leg(hipFar, p.legFar),
    legNear: leg(hipNear, p.legNear),
  };
}

function limb(c, a, b, r0, r1, m) {
  c.part(capsule(a, b, r0, r1), m);
}

function foot(c, ankle, kneeAngle, m, len = 9) {
  const toe = [ankle[0] + len, ankle[1] + 1.5];
  const heel = [ankle[0] - 4.5, ankle[1] + 1.5];
  c.part(
    [
      [heel[0], heel[1] - 4],
      [toe[0], toe[1] - 3.5],
      [toe[0] + 1, toe[1] + 1],
      [heel[0] - 0.5, heel[1] + 1],
    ],
    m,
  );
}

/**
 * Draw a posed humanoid.
 *
 * `cfg` supplies the palette and optional hooks: `back` (drawn behind
 * everything), `torsoDecor`, `head`, `weapon`. The hooks receive the solved
 * skeleton so they can attach to real joints.
 */
export function drawHumanoid(c, cfg, p, P = PROPORTIONS) {
  const s = solve(p, P);
  const skin = cfg.skin;
  // Forearms are their own material so a character can have burnt arms without
  // recolouring his face.
  const forearm = cfg.forearm ?? skin;
  const cloth = cfg.cloth;
  const armour = cfg.armour ?? cloth;
  const boot = cfg.boot ?? armour;
  const glove = cfg.glove ?? boot;
  const far = (m) => ({
    ...m,
    base: tone(m.base, -0.26),
    light: m.base,
    shade: tone(m.base, -0.4),
  });

  cfg.back?.(c, s);

  // Far side of the body first, dimmed — depth without a z-buffer. A rider's
  // far leg is behind the horse, so it is suppressed rather than drawn on top
  // of the barrel.
  if (!cfg.noFarLeg) {
    limb(c, s.legFar.hip, s.legFar.knee, P.legR, P.legR * 0.85, far(cloth));
    limb(c, s.legFar.knee, s.legFar.foot, P.legR * 0.85, P.legR * 0.7, far(boot));
    foot(c, s.legFar.foot, 0, far(boot));
  }
  limb(c, s.armFar.shoulder, s.armFar.elbow, P.armR, P.armR * 0.86, far(cloth));
  limb(c, s.armFar.elbow, s.armFar.hand, P.armR * 0.86, P.armR * 0.72, far(forearm));
  c.part(ellipse(s.armFar.hand[0], s.armFar.hand[1], 3.2, 3.4), far(glove));

  cfg.midBack?.(c, s);

  // Torso
  const sw = P.shoulderW;
  const hw = P.hipW;
  const torso = [
    [s.shoulderC[0] - sw, s.shoulderC[1] + 1],
    [s.shoulderC[0] + sw * 0.92, s.shoulderC[1] + 1],
    [s.chest[0] + sw * 0.86, s.chest[1]],
    [s.waist[0] + hw * 1.02, s.waist[1]],
    [s.waist[0] + hw * 1.05, s.hipY + 3],
    [s.waist[0] - hw * 1.05, s.hipY + 3],
    [s.waist[0] - hw * 1.02, s.waist[1]],
    [s.chest[0] - sw * 0.9, s.chest[1]],
  ];
  c.part(torso, armour);
  cfg.torsoDecor?.(c, s, torso);

  // Near leg
  limb(c, s.legNear.hip, s.legNear.knee, P.legR * 1.05, P.legR * 0.9, cloth);
  limb(c, s.legNear.knee, s.legNear.foot, P.legR * 0.9, P.legR * 0.72, boot);
  foot(c, s.legNear.foot, 0, boot);

  // Head
  const neck = capsule(s.neck, [s.head[0], s.head[1] + P.headRY * 0.6], 4.4, 4.8);
  c.part(neck, skin);
  cfg.head?.(c, s, P);

  // Near arm last so it reads in front of the chest, then the weapon in its hand
  limb(c, s.armNear.shoulder, s.armNear.elbow, P.armR * 1.05, P.armR * 0.9, cloth);
  limb(c, s.armNear.elbow, s.armNear.hand, P.armR * 0.9, P.armR * 0.76, forearm);
  cfg.weapon?.(c, s, p);
  c.part(ellipse(s.armNear.hand[0], s.armNear.hand[1], 2.9, 3.2), glove);

  cfg.front?.(c, s);
  return s;
}

/** A plain rounded head with hair and optional face marks. */
export function drawHead(c, s, P, cfg) {
  const { skin, hair } = cfg;
  const cx = s.head[0];
  const cy = s.head[1];
  const rx = P.headRX;
  const ry = P.headRY;

  // Jaw is pushed forward so the profile reads at small sizes.
  c.part(
    [
      [cx - rx, cy - ry * 0.5],
      [cx - rx * 0.55, cy - ry],
      [cx + rx * 0.5, cy - ry],
      [cx + rx * 0.98, cy - ry * 0.25],
      [cx + rx * 0.95, cy + ry * 0.42],
      [cx + rx * 0.3, cy + ry],
      [cx - rx * 0.5, cy + ry * 0.85],
      [cx - rx * 0.95, cy + ry * 0.2],
    ],
    skin,
  );

  cfg.hairShape?.(c, cx, cy, rx, ry, hair);
  cfg.face?.(c, cx, cy, rx, ry);
}

/**
 * Side-view horse. `p.gait` 0..1 drives the leg cycle; `p.rear` lifts the front
 * end for the charge frames. Origin is the ground under the horse's chest.
 */
export function drawHorse(c, cfg, p) {
  const hide = cfg.hide;
  const mane = cfg.mane;
  const tack = cfg.tack;
  const hoof = cfg.hoof ?? { line: '#141020', base: '#2a2230' };
  const far = (m) => ({
    ...m,
    base: tone(m.base, -0.3),
    light: tone(m.base, -0.14),
    shade: tone(m.base, -0.45),
  });
  const g = p.gait ?? 0;
  const rear = p.rear ?? 0;

  const swing = (ph, amp = 30) => Math.sin((g + ph) * Math.PI * 2) * amp;

  // Everything hangs off the withers height. A rider's hips sit on the saddle,
  // so this number and the rider's hip-to-crown length together decide the
  // sprite's total height.
  const W = -62 + (p.bob ?? 0);
  const lift = -rear * 16;
  const CHEST = 28;
  const RUMP = -34;

  const legs = [
    { top: [CHEST - 5, W + 16 + lift], ph: 0, front: true },
    { top: [RUMP + 9, W + 15], ph: 0.5, front: false },
  ];

  for (const { top, ph, front } of legs) {
    drawLeg(c, top, swing(ph + 0.5), front, far(hide), far(hoof), rear);
  }

  // Tail
  const tailBase = [RUMP - 1, W + 4];
  const tailMid = [tailBase[0] - 9 - g * 2, tailBase[1] + 20];
  const tailTip = [tailBase[0] - 13 - g * 4, tailBase[1] + 40 + Math.sin(g * 6.28) * 5];
  c.part(capsule(tailBase, tailMid, 6, 4.5), mane);
  c.part(capsule(tailMid, tailTip, 4.5, 1.8), mane);

  // Barrel — the single biggest shape on the sprite; if it is short the whole
  // animal reads as a pony.
  c.part(
    [
      [RUMP - 3, W + 8],
      [RUMP + 5, W - 1],
      [2, W - 2 + lift * 0.35],
      [CHEST - 4, W + 1 + lift * 0.8],
      [CHEST + 5, W + 12 + lift * 0.8],
      [CHEST + 1, W + 27 + lift * 0.6],
      [8, W + 32],
      [RUMP + 10, W + 30],
      [RUMP - 2, W + 22],
    ],
    hide,
  );

  // Neck: a wide wedge, not a tube. A thin neck at this scale reads as a llama.
  const poll = [CHEST + 13 + rear * 3, W - 24 - rear * 6];
  c.part(
    [
      [CHEST - 10, W - 2 + lift * 0.7],
      [CHEST + 3, W + 16 + lift * 0.8],
      [poll[0] + 7, poll[1] + 12],
      [poll[0] + 4, poll[1] - 2],
      [poll[0] - 8, poll[1] - 2],
      [CHEST - 15, W + 4 + lift * 0.5],
    ],
    hide,
  );
  // Head: a wedge angled down off the poll, deep at the cheek and narrow at the
  // muzzle. Same width as the neck and it merges into one tube; level instead
  // of angled and it reads as a plank.
  const muzzle = [poll[0] + 14, poll[1] + 20];
  c.part(
    [
      [poll[0] - 7, poll[1] - 4],
      [poll[0] + 4, poll[1] - 2],
      [muzzle[0] + 2, muzzle[1] - 6],
      [muzzle[0] + 3, muzzle[1] + 2],
      [muzzle[0] - 3, muzzle[1] + 3],
      [poll[0] + 3, poll[1] + 12],
      [poll[0] - 8, poll[1] + 8],
    ],
    hide,
  );
  c.part(
    [
      [poll[0] - 5, poll[1] - 5],
      [poll[0] - 7, poll[1] - 14],
      [poll[0] - 1, poll[1] - 5],
    ],
    hide,
  );
  // Mane along the crest
  c.part(
    [
      [CHEST - 13, W + 1],
      [poll[0] - 10, poll[1] - 2],
      [poll[0] - 3, poll[1] - 10],
      [poll[0] - 5, poll[1] + 3],
      [CHEST - 7, W + 7],
    ],
    mane,
  );
  c.poly(ellipse(poll[0] + 3, poll[1] + 4, 1.8, 2.1), '#120c18');
  // Noseband and cheek strap
  c.part(capsule([muzzle[0] + 1, muzzle[1] - 5], [muzzle[0] - 4, muzzle[1] + 1], 1.8, 1.8), tack);
  c.part(capsule([muzzle[0] - 2, muzzle[1] - 3], [poll[0] - 3, poll[1] + 7], 1.6, 1.6), tack);

  // Saddle and blanket
  const saddle = [0, W - 1];
  c.part(
    [
      [saddle[0] - 13, saddle[1] + 3],
      [saddle[0] + 11, saddle[1] + 2],
      [saddle[0] + 14, saddle[1] + 22],
      [saddle[0] - 17, saddle[1] + 24],
    ],
    tack,
  );
  c.part(
    [
      [saddle[0] - 9, saddle[1] - 3],
      [saddle[0] + 8, saddle[1] - 4],
      [saddle[0] + 10, saddle[1] + 4],
      [saddle[0] - 11, saddle[1] + 5],
    ],
    { ...tack, base: tone(tack.base, -0.3) },
  );

  // The rider goes on here — between the saddle and the near legs, so the
  // horse's shoulder overlaps the rider's boot the way it does in life.
  cfg.onSaddle?.(c, saddle);

  for (const { top, ph, front } of legs) {
    drawLeg(c, top, swing(ph), front, hide, hoof, rear);
  }

  return { saddle, withers: W };
}

function drawLeg(c, top, ang, front, hide, hoof, rear) {
  const upper = 22;
  const lower = 18;
  const kneeAng = front ? -ang * 0.5 - rear * 45 : ang * 0.5;
  const knee = along(top, ang - (front ? rear * 60 : 0), upper);
  const fetlock = along(knee, ang + kneeAng, lower);
  const hoofPt = along(fetlock, ang * 0.2, 6);
  c.part(capsule(top, knee, 6.4, 3.9), hide);
  c.part(capsule(knee, fetlock, 3.5, 2.3), hide);
  c.part(capsule(fetlock, hoofPt, 2.4, 3.1), hoof);
}

/** Straight blade with a fuller, pointing along +x from the grip. */
export function drawSword(c, grip, angle, cfg) {
  const { blade, hilt, len = 44, width = 4.2, glow } = cfg;
  c.save();
  c.translate(grip[0], grip[1]);
  c.rotate(angle);
  // Grip runs backwards from the hand, blade forwards. Everything behind the
  // guard is one flat dark shape: a pommel disc and a shaded grip pile up into
  // an unreadable gold lump at 46px.
  const dark = { line: hilt.line, base: tone(hilt.base, -0.42) };
  c.part(
    [
      [-8, -2.6],
      [-6, -1.8],
      [-1, -1.8],
      [-1, 1.8],
      [-6, 1.8],
      [-8, 2.6],
    ],
    dark,
  );
  c.part(
    [
      [-1.2, -4.6],
      [2.2, -3.6],
      [2.2, 3.6],
      [-1.2, 4.6],
    ],
    { line: hilt.line, base: hilt.base },
  );
  c.part(
    [
      [2.5, -width],
      [len * 0.62, -width * 0.78],
      [len - 7, -width * 0.5],
      [len, 0],
      [len - 7, width * 0.5],
      [len * 0.62, width * 0.78],
      [2.5, width],
    ],
    blade,
  );
  if (glow) {
    c.poly(
      [
        [6, -width * 0.3],
        [len * 0.62, -width * 0.26],
        [len - 6, 0],
        [len * 0.62, width * 0.26],
        [6, width * 0.3],
      ],
      glow,
    );
  }
  c.restore();
}

/** Lance: long shaft, leaf head, small counterweight. */
export function drawLance(c, grip, angle, cfg) {
  const { shaft, head, len = 78, back = 22 } = cfg;
  c.save();
  c.translate(grip[0], grip[1]);
  c.rotate(angle);
  c.part(
    [
      [-back, -2.4],
      [len - 16, -2.4],
      [len - 16, 2.4],
      [-back, 2.4],
    ],
    shaft,
  );
  c.part(
    [
      [len - 18, -3.2],
      [len - 12, -5.4],
      [len, 0],
      [len - 12, 5.4],
      [len - 18, 3.2],
    ],
    head,
  );
  c.part(
    [
      [-back - 4, -2.6],
      [-back + 2, -2.6],
      [-back + 2, 2.6],
      [-back - 4, 2.6],
    ],
    head,
  );
  c.restore();
}

/** Two-handed axe with a crescent head. */
export function drawGreatAxe(c, grip, angle, cfg) {
  const { shaft, head, len = 62, glow, headScale: k = 1 } = cfg;
  c.save();
  c.translate(grip[0], grip[1]);
  c.rotate(angle);
  c.part(
    [
      [-24, -3],
      [len, -3],
      [len, 3],
      [-24, 3],
    ],
    shaft,
  );
  // Single-bit bearded axe with a short back spike. A symmetric double-bit head
  // collapses into a paddle once it is small enough to fit the frame.
  const hx = len - 5;
  c.part(
    [
      [hx - 7, -3],
      [hx - 12, -1],
      [hx - 7, 4],
    ],
    head,
  );
  // The bit sits on one side of the haft with a flat underside — a blade that
  // fans out both ways reads as a shovel once it is small enough to fit.
  // Narrow at the socket, broad at the edge. Without that waist the bit reads
  // as a spade however big it is.
  c.part(
    [
      [hx - 7, -4],
      [hx - 2, -11 * k],
      [hx + 2, -30 * k],
      [hx + 13 * k, -24 * k],
      [hx + 18 * k, -8 * k],
      [hx + 12 * k, 4],
      [hx + 1, 8],
      [hx - 7, 5],
    ],
    head,
  );
  if (glow) {
    c.poly(
      [
        [hx + 4, -25 * k],
        [hx + 13 * k, -20 * k],
        [hx + 15 * k, -8 * k],
        [hx + 10 * k, 2],
        [hx + 6, -6 * k],
        [hx + 5, -18 * k],
      ],
      glow,
    );
  }
  c.restore();
}

/** A cape hanging from the shoulders, blown back by `sway`. */
export function drawCape(c, s, m, opts = {}) {
  const { width = 13, len = 62, sway = 0 } = opts;
  const top = [s.shoulderC[0], s.shoulderC[1] - 1];
  const tip = [top[0] - len * 0.42 - sway, top[1] + len];
  const mid = lerp2(top, tip, 0.55);
  c.part(
    [
      [top[0] + width * 0.5, top[1] - 2],
      [top[0] - width, top[1] + 1],
      [mid[0] - width * 0.9 - sway * 0.3, mid[1]],
      [tip[0] - width * 0.5, tip[1] + 4],
      [tip[0] + width * 0.7, tip[1] - 2],
      [mid[0] + width * 0.75, mid[1] - 4],
    ],
    m,
  );
}

export { along, dir };
